context:
  name: easyreflectometry
  version: "1.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyreflectometry-${{ version }}.tar.gz
  sha256: a7bdda2ac40fa9d1b52b103e7debedca6a431eb2d37d940430350b994502267c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - easyscience >=2.5.1
    - scipp
    - refnx
    - refl1d >=1.0.0
    - orsopy
    - if: unix
      then:
        - __unix
        - svglib <1.6
    - xhtml2pdf
    - bumps
    - pooch
    - plotly
    # xhtml2pdf seems to complain about this
    - python-bidi >=0.5.0

tests:
  - python:
      imports:
        - easyreflectometry
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://docs.easyreflectometry.org/
  summary: A reflectometry python package built on the EasyScience framework.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/easyscience/EasyReflectometryLib

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/easyscience
